trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: 'application-springboot'
    type: github
    ref: main
    endpoint: '20220501'
    name: 'oad3/application-springboot'

Public
stages:
- stage: stage_test
  jobs: 
  - job: MyJob
    displayName: MyJob_1
    workspace:
      clean: outputs
    steps:
    - script: ls -la
    - checkout: self
    - checkout: hello_world
    - script: ls -la
