trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: "application-springboot"
      type: github
      ref: main
      endpoint: "20220501"
      name: "oad3/application-springboot"

stages:
  - stage: BuildAndPush
    jobs:
      - job: Build
        displayName: Build
        continueOnError: true
        workspace:
          clean: outputs
        steps:
          - checkout: self
          - checkout: "application-springboot"
          - task: Gradle@2
            inputs:
              gradleWrapperFile: "./application-springboot/gradlew"
              workingDirectory: "./application-springboot"
              tasks: "build"
              publishJUnitResults: true
              testResultsFiles: "**/TEST-*.xml"
              javaHomeOption: "JDKVersion"
              sonarQubeRunAnalysis: false
              spotBugsAnalysis: false
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          - bash: |
              ls -la ./application-springboot/build/libs/

          # - task: Docker@2
          #   displayName: Login to Docker Hub
          #   inputs:
          #     command: login

          # - task: Docker@2
          #   displayName: Build and Push
          #   inputs:
          #     Dockerfile: ./SpringBootDemo/demo/Dockerfile
          #     command: buildAndPush
          #     repository: oad3jp999/oad3_dockerimage_springboot_demo
          #     tags: |
          #       20220417_1
